---
title: "R的数据框操作"
author: "孔令仁"
date: "2020年4月23日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 数据框

数据框是的R重要数据分析工具，类似于python的pandas，也类似于SQL的一个表

## 数据框基本操作

- 数据库的一列是`df$columnname`的格式

- 开头用head函数（默认6个）

- 数值汇总用summary函数

- colnames更改列名

- merge合并数据框，参`数all.x=T`是左连接，左侧全保留（类似SQL左连接）

```{r}
L3 <- LETTERS[1:3]
abc <- sample(L3, 10, replace = TRUE)
d <- data.frame(x = 1, y = 1:10, abc = abc)
d$x
d$y
d$abc
colnames(d)[1] <- 'x1' #数据框第一列名称改成x1
head(d) #默认展示前6个
summary(d) #各列进行描述统计
d2 <- data.frame(x = 2, y = 1:10)
merge(d,d2) #合并数据
```

## 数据框与ddply

```{r}
library(plyr)
set.seed(233)
dfx = data.frame(
  group = c(rep('A', 8), rep('B', 15), rep('C', 6)),
  sex = sample(c("M", "F"), size = 29, replace = TRUE),#repalce可重复抽样
  age = runif(n = 29, min = 18, max = 54)#unif均匀分布的随机抽样
)
head(dfx)
```

```{r}
# nrow是内置函数，计算行数
ddply(dfx,.(group),nrow) #对于变量列group进行分类计数
ddply(dfx,.(group,sex),nrow) #双变量计数
ddply(dfx,.(group,sex),function(s){
  res1 = quantile(s$age,0.25);names(res1) <- NULL
  res2 = quantile(s$age,0.75);names(res2) <- NULL#去除默认名称
  return (c(q25=res1,q75=res2))
})
```
